version: "3"

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'docker'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
  rest-api:
    build: .
    restart: on-failure
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
    - 8080:8080
    links:
      - mysql-db

volumes:
  data:
    driver: "local"
